
---------------------------------------------------------
--  This code is generated by Terasic System Builder
---------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

use work.all;
use work.std_package.all;

entity DE2_Standard is
port
(

	------------ CLOCK ------------
	CLOCK2_50       	:in    	std_ulogic;
	CLOCK3_50       	:in    	std_ulogic;
	CLOCK_50        	:in    	std_ulogic;

	------------ KEY ------------
	KEY             	:in    	std_ulogic_vector(3 downto 0);

	------------ SW ------------
	SW              	:in    	std_ulogic_vector(17 downto 0);

	------------ Seg7 ------------
	HEX0            	:out   	std_ulogic_vector(6 downto 0);
	HEX1            	:out   	std_ulogic_vector(6 downto 0);
	HEX2            	:out   	std_ulogic_vector(6 downto 0);
	HEX3            	:out   	std_ulogic_vector(6 downto 0);
	HEX4            	:out   	std_ulogic_vector(6 downto 0);
	HEX5            	:out   	std_ulogic_vector(6 downto 0);
	HEX7				:out	std_ulogic_vector(6 downto 0);
	
	------------ GPIO ------------
	GPIO				:inout	std_ulogic_vector(35 downto 0);

	------------ LED ------------
	LEDG				:out	std_ulogic_vector(8 downto 0);
	LEDR 				:out 	std_ulogic_vector(17 downto 0);
	
	FAN_CTRL				:inout	std_ulogic
);

end entity;



---------------------------------------------------------
--  Structural coding
---------------------------------------------------------


architecture rtl of DE2_Standard is
	signal sevenseg : std_ulogic_vector (0 to 20);

begin

	FAN_CTRL <= '0';

	tilt : entity work.Tilt_board
	port map (
		clk_i => CLOCK_50,
		rst_i => KEY(0),
		btnIncrement_i => KEY(1),
		btnDecrement_i => KEY(2),
		switchTen_i => SW(0),
		dbg_en_i => SW(1),
		switchMovingAvg_i => SW(2),
		sevenseg_o => sevenseg,
		ServoX_pwm_pin_o => GPIO(0),
		x_pwm_pin_o => GPIO(1),
		x_comp_async_i => GPIO(2),
		dbg_adc_val_o => LEDR(ADC_BIT_WIDTH - 1 downto 0)
	);
	
	HEX0 <= sevenseg(6 downto 0);
	HEX1 <= sevenseg(13 downto 7);
	HEX2 <= sevenseg(20 downto 14);

end rtl;

