
---------------------------------------------------------
--  This code is generated by Terasic System Builder
---------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

use work.all;
use work.std_package.all;

entity DE2_Standard is
port
(

	------------ CLOCK ------------
	CLOCK2_50       	:in    	std_ulogic;
	CLOCK3_50       	:in    	std_ulogic;
	CLOCK_50        	:in    	std_ulogic;

	------------ KEY ------------
	KEY             	:in    	std_ulogic_vector(3 downto 0);

	------------ SW ------------
	SW              	:in    	std_ulogic_vector(17 downto 0);

	------------ Seg7 ------------
	HEX0            	:out   	std_ulogic_vector(0 to 6);
	HEX1            	:out   	std_ulogic_vector(0 to 6);
	HEX2            	:out   	std_ulogic_vector(0 to 6);
	HEX3            	:out   	std_ulogic_vector(0 to 6);
	HEX4            	:out   	std_ulogic_vector(0 to 6);
	HEX5            	:out   	std_ulogic_vector(0 to 6);
	HEX7					:out		std_ulogic_vector(0 to 6);
	
	------------ GPIO ------------
	GPIO				:inout	std_ulogic_vector(35 downto 0);

	------------ LED ------------
	LEDG				:out	std_ulogic_vector(8 downto 0);
	LEDR 				:out 	std_ulogic_vector(17 downto 0);
	
	FAN_CTRL				:inout	std_ulogic
);

end entity;



---------------------------------------------------------
--  Structural coding
---------------------------------------------------------


architecture rtl of DE2_Standard is
	signal sevenseg_x : std_ulogic_vector (0 to 20);
	signal sevenseg_y : std_ulogic_vector (0 to 20);

begin

	FAN_CTRL <= '0';

	axis_controller : entity work.axis_controller
	port map (
		clk_i => CLOCK_50,

		rst_i => KEY(0),
		btn_dbg_inc_async => KEY(1),
		btn_dbg_dec_async => KEY(2),
		btn_drawK_async => KEY(3),

		sw_dbg_10_async => SW(0),
		sw_en_dbg_async => SW(1),
		sw_en_filter_async => SW(2),
		sw_dbg_y_axis_async => SW(3),
		sw_z_axis_async => SW(4),

		ServoX_pwm_pin_o => GPIO(0),
		ServoY_pwm_pin_o => GPIO(1),
		ServoZ_pwm_pin_o => GPIO(2),
		x_pwm_pin_o => GPIO(3),
		y_pwm_pin_o => GPIO(4),
		x_comp_async => GPIO(5),
		y_comp_async => GPIO(6),

		x_sevenseg_o => sevenseg_x,
		y_sevenseg_o => sevenseg_y,

		dbg_strb_o => GPIO(7)

	);
	
	HEX0 <= sevenseg_x(0 to 6);
	HEX1 <= sevenseg_x(7 to 13);
	HEX2 <= sevenseg_x(14 to 20);

	HEX3 <= sevenseg_y(0 to 6);
	HEX4 <= sevenseg_y(7 to 13);
	HEX5 <= sevenseg_y(14 to 20);



end rtl;

